const actions = {
  SWITCH_THEME: "SWITCH_THEME",
  SWITCH_LANGUAGE: "SWITCH_LANGUAGE",
  SET_USER_METADATA: "SET_USER_METADATA",
  SET_USER_METADATA: "SET_USER_METADATA",
  GET_USER_METADATA: "GET_USER_METADATA",
};

export {
  actions,
};
